In [1]:
#import scanpy as sc
import anndata
import numpy as np
import pandas as pd
import importlib
#import pickle

import sys
sys.path.append("..")
import autogenes

In [2]:
data = pd.read_csv('../datasets/GSE75748_bulk_data.csv',index_col='index')
data = data.T.iloc[:,:100].values
ag = autogenes.AutoGeneS(data)

In [3]:
ag.run(ngen=10,offspring_size=100,seed=0,weights=(1,),objectives=('distance',))

gen	nevals	pareto	distance     
0  	100   	1     	8.27 - 237.81
1  	100   	1     	68.86 - 237.81
2  	100   	1     	141.96 - 237.81
3  	100   	1     	159.75 - 237.81
4  	100   	1     	166.6 - 237.81 
5  	100   	1     	230.26 - 237.81
6  	100   	1     	233.67 - 237.81
7  	100   	1     	233.67 - 237.81
8  	100   	1     	237.81 - 237.81
9  	100   	1     	237.81 - 237.81
10 	100   	1     	237.81 - 237.81


In [4]:
ag.fitness_matrix

array([[237.8142811]])

In [5]:
ag.plot(objectives=(0,0))

Exception: Cannot plot for a single objective

In [6]:
ag.run(ngen=10,offspring_size=100,seed=0,weights=(-1,),objectives=('correlation',))

gen	nevals	pareto	correlation 
0  	100   	1     	3.56 - 14.24
1  	100   	1     	3.56 - 8.08 
2  	100   	1     	3.56 - 6.18 
3  	100   	1     	3.56 - 5.2  
4  	100   	1     	3.56 - 4.4  
5  	100   	1     	3.56 - 4.23 
6  	100   	1     	3.56 - 4.0  
7  	100   	1     	3.56 - 4.0  
8  	100   	1     	3.56 - 3.56 
9  	100   	1     	3.56 - 3.56 
10 	100   	1     	3.56 - 3.56 


In [7]:
ag.fitness_matrix

array([[3.55701193]])

In [8]:
ag.run(ngen=10,offspring_size=100,seed=0,weights=(1,0),objectives=('distance','correlation'))

../autogenes/core.py:84: UserWarning: Ignoring objective 'correlation'
  warnings.warn(f"Ignoring objective '{str(objectives[i])}'")


gen	nevals	pareto	distance     
0  	100   	1     	8.27 - 237.81
1  	100   	1     	68.86 - 237.81
2  	100   	1     	141.96 - 237.81
3  	100   	1     	159.75 - 237.81
4  	100   	1     	166.6 - 237.81 
5  	100   	1     	230.26 - 237.81
6  	100   	1     	233.67 - 237.81
7  	100   	1     	233.67 - 237.81
8  	100   	1     	237.81 - 237.81
9  	100   	1     	237.81 - 237.81
10 	100   	1     	237.81 - 237.81


In [9]:
ag.fitness_matrix

array([[237.8142811]])

In [10]:
ag.pareto[0].fitness.wvalues

(237.81428109547008,)

In [11]:
def num_genes(data): return data.shape[0]
ag.run(ngen=10,offspring_size=100,seed=0,weights=(1,-1,0),objectives=('distance',num_genes,'correlation'))

gen	nevals	pareto	distance     	num_genes
0  	100   	1     	8.27 - 237.81	6.0 - 6.0
1  	100   	1     	68.86 - 237.81	6.0 - 6.0
2  	100   	1     	141.96 - 237.81	6.0 - 6.0
3  	100   	1     	159.75 - 237.81	6.0 - 6.0
4  	100   	1     	166.6 - 237.81 	6.0 - 6.0
5  	100   	1     	230.26 - 237.81	6.0 - 6.0
6  	100   	1     	233.67 - 237.81	6.0 - 6.0
7  	100   	1     	233.67 - 237.81	6.0 - 6.0
8  	100   	1     	237.81 - 237.81	6.0 - 6.0
9  	100   	1     	237.81 - 237.81	6.0 - 6.0
10 	100   	1     	237.81 - 237.81	6.0 - 6.0


In [12]:
ag.select()

IndividualGA([False, False, False, False,  True, False, False,  True,
              False, False, False, False, False, False, False, False,
               True, False, False, False, False, False, False, False,
               True, False, False, False, False,  True, False, False,
              False, False, False, False, False, False, False, False,
              False, False,  True, False, False,  True, False,  True,
               True, False, False, False, False,  True, False, False,
               True,  True, False, False, False, False, False, False,
               True, False, False, False, False, False, False, False,
              False,  True, False, False, False, False,  True, False,
              False, False, False,  True, False,  True, False, False,
              False, False, False, False, False, False, False, False,
              False,  True, False, False])

In [13]:
ag.run(ngen=10,offspring_size=100,seed=0,weights=(1,-1,0.5),objectives=('distance',num_genes,'correlation'),verbose=False)

In [14]:
ag.select()

IndividualGA([False, False, False, False, False,  True, False, False,
               True,  True,  True, False, False, False, False, False,
              False, False, False, False, False, False, False, False,
              False, False, False, False, False, False, False, False,
               True,  True,  True,  True, False, False, False, False,
              False, False, False, False, False,  True, False, False,
               True, False, False, False, False, False, False, False,
              False, False, False, False, False, False,  True, False,
               True,  True, False, False, False, False, False, False,
              False, False, False, False, False, False, False,  True,
              False, False, False, False, False, False, False,  True,
              False, False, False, False, False, False, False, False,
               True, False, False, False])